apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
  labels:
    run: reverseproxy-prod
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: reverseproxy-prod
